# -*- coding: utf-8 -*-
"""kelly.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Sbupz2qnpD7tLEPaUVOHqZ0xyMnQDlFY
"""

# Importar as bibliotecas necessárias
import orender

# Definir a função que será chamada pelo Orender
@orender.code
def calcular_kelly(probabilidade, odd, stake):
    # Cálculo do Critério Kelly
    p = probabilidade / 100
    q = 1 - p
    b = odd - 1

    kelly_fraction = (b * p - q) / b

    # Verificação para evitar porcentagem negativa
    if kelly_fraction < 0:
        kelly_fraction = 0

    # Cálculo do valor em reais a ser apostado
    valor_apostado = kelly_fraction * stake

    # Retornar o resultado
    return {
        "porcentagem_stake": kelly_fraction * 100,
        "valor_apostado": valor_apostado
    }

# Executar o código
resultado = calcular_kelly(probabilidade, odd, stake)

# Exibir o resultado
print("Porcentagem da stake a ser apostada: {:.2f}%".format(resultado["porcentagem_stake"]))
print("Valor em reais a ser apostado: R$ {:.2f}".format(resultado["valor_apostado"]))